platform :ios, "12.0" 						#手机系统版本

target "QMapScenariosDemo" do					#工程的名字
  pod 'Tencent-MapSDK', '6.1.0'
  pod 'Tencent-MapVisualPlugin', '>=3.1.3'
  pod 'Tencent-MapFoundation', '>=4.1.5'
  pod 'Tencent-MapUtils', '>=1.2.4'
end

#当有多个target时，不同的target也需要各自设置
#target "QMapKitDemo1" do					#工程的名字
#	pod 'Tencent-MapSDK'					  #地图SDK
#end

#target "QMapKitDemo2" do					#工程的名字
#	pod 'Tencent-MapSDK'					  #地图SDK
#end
