platform :ios, "9.0" 						#手机系统版本
target "QMapScenarioDemo" do					#工程的名字
  pod 'Tencent-MapSDK'					#地图SDK
end

#当有多个target时，不同的target也需要各自设置
#target "QMapKitDemo1" do					#工程的名字
#	pod 'Tencent-MapSDK'					  #地图SDK
#end

#target "QMapKitDemo2" do					#工程的名字
#	pod 'Tencent-MapSDK'					  #地图SDK
#end
